-- MySQL Script generated by MySQL Workbench
-- 03/09/18 09:31:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coffee` ;

-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee` DEFAULT CHARACTER SET utf8 ;
USE `coffee` ;

-- -----------------------------------------------------
-- Table `coffee`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(32) NULL,
  `subtitle` VARCHAR(32) NULL,
  `image` VARCHAR(255) NULL,
  `text` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `coffee`.`products`
-- -----------------------------------------------------
START TRANSACTION;
USE `coffee`;
INSERT INTO `coffee`.`products` (`id`, `title`, `subtitle`, `image`, `text`) VALUES (1, 'Coffees & Teas', 'Blended to Perfection', 'img/products-01.jpg', 'We take pride in our work, and it shows. Every time you order a beverage from us, we guarantee that it will be an experience worth having. Whether it\'s our world famous Venezuelan Cappuccino, a refreshing iced herbal tea, or something as simple as a cup of speciality sourced black coffee, you will be coming back for more.');
INSERT INTO `coffee`.`products` (`id`, `title`, `subtitle`, `image`, `text`) VALUES (2, 'Bakery & Kitchen', 'Delicious Treats, Good Eats', 'img/products-02.jpg', 'Our seasonal menu features delicious snacks, baked goods, and even full meals perfect for breakfast or lunchtime. We source our ingredients from local, oragnic farms whenever possible, alongside premium vendors for specialty goods.');
INSERT INTO `coffee`.`products` (`id`, `title`, `subtitle`, `image`, `text`) VALUES (3, 'Bulk Speciality Blends', 'From Around the World', 'img/products-03.jpg', 'Travelling the world for the very best quality coffee is something take pride in. When you visit us, you\'ll always find new blends from around the world, mainly from regions in Central and South America. We sell our blends in smaller to large bulk quantities. Please visit us in person for more details.');

COMMIT;

